// Navigation
export const LOG_IN = 'LOG_IN';
export const SET_LOGGED_IN_STATE = 'SET_LOGGED_IN_STATE';

export const C_EVENTSTART = "CREATE_EVENTSTART"
export const C_EVENTSUCCESS = "CREATE_EVENTSUCCESS"
export const C_EVENTFAILURE = "CREATE_EVENTFAILURE"

export const U_EVENTSTART = "UPDATE_EVENTSTART"
export const U_EVENTSUCCESS = "UPDATE_EVENTSUCCESS"
export const U_EVENTFAILURE = "UPDATE_EVENTFAILURE"